# Generated by Django 3.2.7 on 2024-06-28 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('railways', '0002_order_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='railways.station'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='railways.station'),
        ),
    ]
